---
config:
  prefix: "c!"
  administrators: [
    "986696962457878588", # Administrator Role
    "662292327477542913" # Thenlie  
  ]
  moderators: [
    "986696511238836234" # Moderator Role
  ]
  restricted_users: []
  whitelist_domains: [
    "github",
    "hastebin",
    "privatebin"
  ]
  whitelist_languages: [
    "javascript",
    "js",
    "java",
    "python",
    "py",
    "c++",
    "cpp",
  ]