---
config:
  prefix: "c!"
  administrator: [
    "986696962457878588", # Administrator Role
    "662292327477542913" # Thenlie  
  ]
  moderator: [
    "986696511238836234" # Moderator Role
  ]
  restricted_users: []